#contoh programan aritmatika
nama = input("Masukkan nama Anda  = ")
nim = input("Masukkan NIM Anda = ")
tugas = input("Tugas ke ")
print("Nama = ",nama)
print("NIM = ",nim)
print("Tugas Ke ",tugas)
print(30*"*")
print("Tugas")
print("")
nilai1 = int(input("angka pertama = "))
nilai2 = int(input("angka kedua = "))    
print(nilai1,"+",nilai2,"=",nilai1 + nilai2)
print(nilai1,"-",nilai2,"=",nilai1 - nilai2)
print(nilai1,"/",nilai2,"=",nilai1 / nilai2)
print(nilai1,"//",nilai2,"=",nilai1 // nilai2)
print(nilai1,"%",nilai2,"=",nilai1 % nilai2)
print(nilai1,"*",nilai2,"=",nilai1 * nilai2)
print(nilai1,"**",nilai2,"=",nilai1 ** nilai2)